config/routes.rb
Rails.application.routes.draw do
  root "shifts#new"
  get 'static_pages/home', to: 'static_pages#home', as: :home
  get 'static_pages/help', to: 'static_pages#help', as: :help
  get 'shifts/share', to: 'shifts#share', as: :share
  get 'shifts/show/:token', to: 'shifts#show', as: :show
  get 'shifts/determined/:token', to: 'shifts#determined', as: :determined
  resources :shifts
  resources :worker_desires
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/weekday_people_validator.rb
class WeekdayPeopleValidator < ActiveModel::Validator
    def validate(record)
        (0..47).each do |time|
            (0..6).each do |week_day|
                attribute_name = "week_day_#{time}_#{week_day}"
                value = record.send(attribute_name)
                unless value.is_a?(Integer) && value >= 0
                    record.errors.add(attribute_name, "must be a non-negative integer")
                end
            end
        end
    end
end

app/models/shift.rb
class Shift < ApplicationRecord
    has_many :worker_desires, dependent: :destroy
    include ActiveModel::Validations
    validates_with WeekdayPeopleValidator

    class << self
        def id_to_token(id)
            Base64.urlsafe_encode64(id.to_s)
        end

        def token_to_id(token)
            Base64.urlsafe_decode64(token)
        end
    end

    # 各時間帯ごとの必要な人数のカラムを指定
    (0..47).each do |time|
        (0..6).each do |week_day|
            define_method("week_day_#{time}_#{week_day}") { read_attribute("week_day_#{time}_#{week_day}") }
            define_method("week_day_#{time}_#{week_day}=") { |value| write_attribute("week_day_#{time}_#{week_day}", value) }
        end
    end

    def int_to_day(int)
        days = %w[monday tuesday wednesday thursday friday saturday sunday]
        days[int]
    end

    def timeInt_to_string(time)
        hour = time / 2
        minute = (time % 2) * 30
        if minute == 0
            minute = "00"
        end
        return "#{hour}:#{minute}"
    end

    def timeString_to_int(time)
        hour = time.split(":")[0].to_i
        minute = time.split(":")[1].to_i
        return hour * 2 + minute / 30
    end

    def time_to_int(time)
        return time.hour * 2 + time.min / 30
    end

    def is_enough_worker(shift)
        (0..6).each do |week_day|
            (0..47).each do |time|
                people_work = 0
                shift.worker_desires.each do |worker|
                    if worker.send("determined_start_#{int_to_day(week_day)}").nil? || worker.send("determined_end_#{int_to_day(week_day)}").nil?
                        next
                    end
                    worker_start = timeString_to_int( worker.send("determined_start_#{int_to_day(week_day)}") )
                    worker_end = timeString_to_int( worker.send("determined_end_#{int_to_day(week_day)}") )
                    if worker_start <= time && time <= worker_end
                        people_work += 1
                    end
                end
                if people_work < shift.send("week_day_#{time}_#{week_day}")
                    return false
                end
            end
        end
        return true
    end

    def distribute_worker(shift)
        workers = shift.worker_desires.shuffle #毎回結果が異なるようにシャッフル
        people_added = Array.new(48) { Array.new(7) }
        (0..6).each do |week_day|
            (0..47).each do |time|
                people_needed = shift.send("week_day_#{time}_#{week_day}") 
                people_added[time][week_day] = 0
                # その時間に必要な人数が0より大きい場合に従業員を探す
                if people_needed > 0
                    workers.each do |worker|
                        worker_start = time_to_int( worker.send("start_time_#{int_to_day(week_day)}") )
                        worker_end = time_to_int( worker.send("end_time_#{int_to_day(week_day)}") )
                        # 従業員がその時間に働ける場合に追加（必要な人数が途中だけ少なくなるデータでは上手くいかない）
                        if worker_start <= time && time <= worker_end
                            people_added[time][week_day] += 1
                            if worker.send("determined_start_#{int_to_day(week_day)}").nil?
                                worker.send("determined_start_#{int_to_day(week_day)}=", timeInt_to_string(time))
                            end
                            # shiftモデルとworker_desireモデルは時間軸が異なるため、1時間後の時間帯を指定するために+1している
                            worker.send("determined_end_#{int_to_day(week_day)}=", timeInt_to_string(time + 1))
                        end
                        # 必要な人数に達したら次の時間帯へ
                        if people_needed == people_added[time][week_day]
                            break
                        end
                    end
                end
            end
        end
    end
end

app/models/worker_desire.rb
class WorkerDesire < ApplicationRecord
  belongs_to :shift
  validates :name, presence: true

  # 各曜日で開始時間が終了時間よりも前になっているかを検証
  DAYS = %w[monday tuesday wednesday thursday friday saturday sunday]
  DAYS.each do |day|
    validate do
      start_time = send("start_time_#{day}")
      end_time = send("end_time_#{day}")

      if start_time.nil? || end_time.nil?
        errors.add("start_time_#{day}", "must be present")

      elsif start_time > end_time
        errors.add("start_time_#{day}", "must be before end time")
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
    def new
    end

    def create
        @shift = Shift.new(shift_params)
        if @shift.save
            shift_id = @shift.id # Get the id of @shift
            flash[:success] = "保存成功"
            link = Shift.id_to_token(@shift.id)
            id_from_link = Shift.token_to_id(link)
            redirect_to share_path(link)
        else
            flash.now[:danger] = "保存失敗"
            render :new
        end
    end
    
    def show
        token = params[:token].to_s
        shift_id = Shift.token_to_id(token)
        @shift = Shift.find_by(id: shift_id)

        unless @shift
            flash[:danger] = "共有先が見つかりません。URLを確認してください"
            render :new
        end
    end

    def destroy
    end

    def share
    end

    def determined
        token = params[:token].to_s
        shift_id = Shift.token_to_id(token)
        @shift = Shift.find_by(id: shift_id)
        
        unless @shift
            flash[:danger] = "共有先が見つかりません。URLを確認してください"
            render :new
        end

        @shift.distribute_worker(@shift)

        if @shift.save
            if @shift.is_enough_worker(@shift)
                flash[:success] = "シフトが作成されました"
            else
                flash[:danger] = "人数が足りない時間があります"
            end
        else
            flash[:danger] = "データが正しいか確認してください"
            redirect_to show_path(token)
        end
    end

    private
        def shift_params
            allowed_params = (0..47).map do |time|
                (0..6).map do |week_day|
                    "week_day_#{time}_#{week_day}".to_sym
                end
            end
            params.require(:shift).permit(allowed_params)
        end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/worker_desires_controller.rb
class WorkerDesiresController < ApplicationController
    
    def new
    end

    def create
        @shift = Shift.find_by(id: params[:worker_desire][:shift_id])
        @worker_desire = @shift.worker_desires.build(worker_desire_params)
        if @worker_desire.save
            flash[:success] = "保存成功"
        else
            flash[:danger] = "保存失敗"
            puts @worker_desire.errors.full_messages
        end
        redirect_to request.referrer || root_url
    end

    private
    def worker_desire_params
    params.require(:worker_desire).permit(:shift_id, :name, :comment, :start_time_monday, :end_time_monday,
                                     :start_time_tuesday, :end_time_tuesday,
                                     :start_time_wednesday, :end_time_wednesday,
                                     :start_time_thursday, :end_time_thursday,
                                     :start_time_friday, :end_time_friday,
                                     :start_time_saturday, :end_time_saturday,
                                     :start_time_sunday, :end_time_sunday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/worker_desire_helper.rb
module WorkerDesireHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white text-center py-2 mt-5">
    <p>&copy; Kuboichi. All rights reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-dark text-white text-center py-2">
    <h1>シフト作成</h1>
    <nav>
        <ul class="nav justify-content-center">
            <li class="nav-item"><%= link_to 'Create', new_shift_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Help', help_path, class: 'nav-link' %></li>
        </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>ShiftCreator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>
  <body>
    <div class="content">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/share_calendar/new.html.erb
<div class="container">
  <p class="h6">以下のURLをアルバイトの方に共有して下さい。</p>
  <div class="input-group mb-3">
    <!-- リンクを一時的にroot_urlにしている -->
    <input type="text" class="form-control" id="sharedUrl" value="<%= root_url %>" readonly>
    <button class="btn btn-outline-secondary" type="button" onclick="copySharedUrl()">コピー</button>
  </div>
  
  <!-- リンクを一時的にroot_urlにしている -->
  <a href="<%= root_url %>" class="btn btn-primary">共有URLへアクセス</a>
</div>

<script>
  function copySharedUrl() {
    const sharedUrlInput = document.getElementById('sharedUrl');
    sharedUrlInput.select();
    sharedUrlInput.setSelectionRange(0, 99999);
    document.execCommand('copy');
    alert('コピーしました: ' + sharedUrlInput.value);
  }
</script>

app/views/shifts/determined.html.erb
<% japanese_days = ["月", "火", "水", "木", "金", "土", "日"] %>
<% puts @shift.worker_desires.inspect %>
<h2>作成されたシフト</h2>
<table class="shiftTable">
  <thead class="thead-dark">
    <tr>
      <th scope="col">名前</th>
      <% japanese_days.each do |day| %>
        <th scope="col"><%= day %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @shift.worker_desires.each do |worker| %>
      <tr>
        <td><%= worker.name %></td>
        <% days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'] %>
        <% days.each do |day| %>
          <td>
            <% if worker.send("start_time_#{day}") == worker.send("end_time_#{day}") %>
              x
            <% else %>
                <%= worker.send("determined_start_#{day}") %> ~ <%= worker.send("determined_end_#{day}") %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'javascript:history.back()' do %>
  <button>提出済みシフト一覧ページに戻る</button>
<% end %>

app/views/shifts/new.html.erb
<% japanese_days = ["月", "火", "水", "木", "金", "土", "日"] %>
<% hours = (0..23).to_a %>
<% minutes = [0, 30] %>


<h1>各時間に必要な人数</h1>

<%# 最初の入力欄をやりやすくする方法。いったん中止。 %>
<%
=begin
%>
<button class= "btn btn-primary" id= "addShiftButton" >入力欄を増やす</button>


<table id="shiftRegisterTable" class="table">
  <thead class="thead-dark">
    <tr>
      <th>曜日</th>
      <th>開始時間</th>
      <th>終了時間</th>
      <th>必要な人数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <select class="form-control">
          <% japanese_days.each do |day| %>
            <option value="<%= day %>"><%= day %></option>
          <% end %>
        </select>
      </td>
      <td>
        <select class="form-control">
          <% hours.each do |hour| %>
            <% minutes.each do |minute| %>
              <option value="<%= Time.parse(hour.to_s + ":" + minute.to_s) %>"><%= hour %>:<%= format('%02d', minute) %></option>
            <% end %>
          <% end %>
        </select>
      </td>
      <td>
        <select class="form-control">
          <% hours.each do |hour| %>
            <% minutes.each do |minute| %>
              <option value="<%= Time.parse(hour.to_s + ":" + minute.to_s) %>"><%= hour %>:<%= format('%02d', minute) %></option>
            <% end %>
          <% end %>
        </select>
      </td>
      <td>
        <select class="form-control">
          <% (0..10).each do |num| %>
            <option value="<%= num %>"><%= num %></option>
          <% end %>
        </select>
    </tr>
  </tbody>
</table>

<%
=end
%>

<%= form_with(model: Shift.new, url: shifts_path, method: :post) do |form| %>
  <table border="1">
    <thead>
      <tr>
        <th></th> <!-- Empty cell for spacing -->
        <th>月</th>
        <th>火</th>
        <th>水</th>
        <th>木</th>
        <th>金</th>
        <th>土</th>
        <th>日</th>
      </tr>
    </thead>
    <tbody>
      <% (0..47).each do |time| %>
        <tr>
          <td> <!-- Format as 00:00, 00:30, 01:00, ..., 23:30 -->
            <%= format('%02d', (time * 30) / 60) %>:<%= format('%02d', (time * 30) % 60) %>
          </td> 
          <% (0..6).each do |week_day| %>
            <td>
              <%= form.number_field "week_day_#{time}_#{week_day}", value: 0, min: 0 %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= form.submit "保存" %>
<% end %>

<script>
  document.getElementById("addShiftButton").addEventListener("click", function() {
    var table = document.getElementById("shiftRegisterTable");
    var newRow = table.insertRow(-1);

    // Create cells for the new row
    var dayCell = newRow.insertCell(0);
    var startTimeCell = newRow.insertCell(1);
    var endTimeCell = newRow.insertCell(2);
    var requiredPeopleCell = newRow.insertCell(3);

    // Set the content of the cells
    dayCell.innerHTML = '<select class="form-control"><% japanese_days.each do |day| %><option value="<%= day %>"><%= day %></option><% end %></select>';
    startTimeCell.innerHTML = '<select class="form-control"><% hours.each do |hour| %><% minutes.each do |minute| %><option value="<%= Time.parse(hour.to_s + ":" + minute.to_s) %>"><%= hour %>:<%= format('%02d', minute) %></option><% end %><% end %></select>';
    endTimeCell.innerHTML = '<select class="form-control"><% hours.each do |hour| %><% minutes.each do |minute| %><option value="<%= Time.parse(hour.to_s + ":" + minute.to_s) %>"><%= hour %>:<%= format('%02d', minute) %></option><% end %><% end %></select>';
    requiredPeopleCell.innerHTML = '<select class="form-control"><% (0..10).each do |num| %><option value="<%= num %>"><%= num %></option><% end %></select>';
  });
</script>

app/views/shifts/share.html.erb
<div class="container">
    <p class="h6">以下のURLをアルバイトの方に共有して下さい。</p>
    <div class="input-group mb-3">
        <input type="text" class="form-control" id="sharedUrl" readonly>
        <button class="btn btn-outline-secondary" type="button" onclick="copySharedUrl()">コピー</button>
    </div>

    <%= link_to "共有URLへアクセス", "#", class: "btn btn-primary", id: "sharedLink" %>
</div>

<script>
    function copySharedUrl() {
        const sharedUrlInput = document.getElementById('sharedUrl');
        sharedUrlInput.select();
        sharedUrlInput.setSelectionRange(0, 99999);
        document.execCommand('copy');
        alert('コピーしました: ' + sharedUrlInput.value);
    }
                
    // 現在のリンクを取得する関数
    function getCurrentUrl() {
        return window.location.href;
    }

    // ページが読み込まれたときにURLを設定
    window.onload = function() {
        const sharedUrl = getCurrentUrl();
        const originUrl = sharedUrl.split('share.')[0];
        const token = sharedUrl.split('share.')[1];
        const Url = originUrl + 'show/' + token;
        document.getElementById('sharedUrl').value = Url;
        document.getElementById('sharedLink').href = Url;
    }
</script>

app/views/shifts/show.html.erb
<% japanese_days = ["月", "火", "水", "木", "金", "土", "日"] %>
<% hours = (0..23).to_a %>
<% minutes = [0, 30] %>

<div class="text-center btn-space">
  <button id="showTable" class="btn btn-primary">シフトの希望を入力する</button>
</div>

<table id="submitTable" class="table" style="display: none;">
  <thead class="thead-dark">
    <tr>
      <th>曜日</th>
      <th>開始時間</th>
      <th>終了時間</th>
    </tr>
  </thead>
  <tbody>
    <% japanese_days.each do |day| %>
      <tr>
        <td><%= day %></td>
        <td>
          <select class="form-control">
            <% hours.each do |hour| %>
              <% minutes.each do |minute| %>
                <option value="<%= Time.parse(hour.to_s + ":" + minute.to_s) %>"><%= hour %>:<%= format('%02d', minute) %></option>
              <% end %>
            <% end %>
          </select>
        </td>
        <td>
          <select class="form-control">
            <% hours.each do |hour| %>
              <% minutes.each do |minute| %>
                <option value="<%= Time.parse(hour.to_s + ":" + minute.to_s) %>"><%= hour %>:<%= format('%02d', minute) %></option>
              <% end %>
            <% end %>
          </select>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= form_with(model: WorkerDesire.new, url: worker_desires_path, method: :post) do |form| %>
  <%= form.number_field :shift_id, id: "shiftID", style: "display: none;", value: @shift.id %>
  <div id="inputFields" style="display: none;">
    <div class="form-group col-md-2 position-relative">
      <label for="name">名前:</label><br>
      <%= form.text_field :name, id: "name", class: "form-control" %><br>
    </div>
    <div class="form-group col-md-5 position-relative">
      <label for="comment">コメント:</label><br>
      <%= form.text_area :comment, id: "comment", class: "form-control" %><br>
    </div>
    <% days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'] %>
    <% days.each do |day| %>
      <%= form.hidden_field "start_time_#{day}".to_sym, id: "start_time_#{day}" %>
      <%= form.hidden_field "end_time_#{day}".to_sym, id: "end_time_#{day}" %>
    <% end %>
    <%= form.submit "シフトの希望を提出する", id: "submitButton" %>
  </div>
<% end %> 

<div class=container>
  <h2>提出済みのシフト</h2>
  <table class="workerTable">
    <% if @shift.worker_desires.count >= 1 %>
      <thead class="thead-dark">
        <tr>
          <th scope="col">名前</th>
          <% japanese_days.each do |day| %>
            <th scope="col"><%= day %></th>
          <% end %>
          <th scope="col">コメント</th>
        </tr>
      </thead>
      <tbody>
        <% @shift.worker_desires.each do |worker| %>
          <tr>
            <td><%= worker.name %></td>
            <% days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'] %>
            <% days.each do |day| %>
              <td>
                <% if worker.send("start_time_#{day}") == worker.send("end_time_#{day}") %>
                  x
                <% else %>
                  <%= worker.send("start_time_#{day}").strftime('%H:%M') %> ~ <%= worker.send("end_time_#{day}").strftime('%H:%M') %>
                <% end %>
              </td>
            <% end %>
            <td><%= worker.comment %></td>
          </tr>
        <% end %>
      </tbody>
    <% else %>
      <p>まだ一つもシフトは提出されていません。</p>
    <% end %>
  </table>

  <%= link_to "提出済みのシフトからシフト表を作成する", determined_path(Shift.id_to_token(@shift.id)), class: "btn btn-primary", id: "createShift" %>
</div>

<script>
// 「入力する」ボタンを押したときにテーブルなどを表示して、ボタンを非表示にする
  document.getElementById('showTable').addEventListener('click', function() {
    document.getElementById('submitTable').style.display = 'table';
    this.style.display = 'none';
    document.getElementById('inputFields').style.display = 'block';
    document.getElementById('submitButton').style.display = 'block';
  });

  document.getElementById('submitButton').addEventListener('click', function() {
    // 「提出する」ボタンを押したときに始めの状態に戻す
    document.getElementById('submitTable').style.display = 'none';
    this.style.display = 'none';
    document.getElementById('inputFields').style.display = 'none';
    document.getElementById('showTable').style.display = 'block';

    // テーブルの値をフォームに入れる
    var days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
    var rows = document.getElementById('submitTable').getElementsByTagName('tr');
    for (var i = 1; i < rows.length; i++) {
      var day = days[i-1];
      var startTimeSelect = rows[i].getElementsByTagName('select')[0];
      var endTimeSelect = rows[i].getElementsByTagName('select')[1];
      document.getElementById('start_time_' + day).value = startTimeSelect.options[startTimeSelect.selectedIndex].value;
      document.getElementById('end_time_' + day).value = endTimeSelect.options[endTimeSelect.selectedIndex].value;
    }
  });
</script>

app/views/static_pages/help.html.erb
<div class="container mt-5">
    <h2>よくある質問</h2>
    <div class="faq-container">
        <div class="faq-item" onclick="toggleAnswer(1)">Q.基本的な使い方を教えてください</div>
        <div class="faq-answer" id="answer1">
            <p>A.ページ上部のCreateを押して、必要な人数を入力します。</p>
            <p>共有リンクが作成されるので従業員に共有してください。</p>
            <p>従業員全員が希望のシフトを入力した後にシフトを作成ボタンを押すことでシフトを作成することが出来ます。</p>
        </div>
        <div class="faq-item" onclick="toggleAnswer(2)">Q.機能を追加される予定はありますか？</div>
        <div class="faq-answer" id="answer2">A.はい。このサイトはまだ未完成で使いやすさや機能の充実性を随時高めていきます。</div>
    </div>
</div>

<script>
  function toggleAnswer(id) {
    var answer = document.getElementById('answer' + id);
    if (answer.style.display === 'none') {
      answer.style.display = 'block';
    } else {
      answer.style.display = 'none';
    }
  }
</script>

app/views/static_pages/home.html.erb
<div class="container mt-5">
    <h1>ページ準備中</h1>
</div>